# Generated by Django 5.1.4 on 2025-01-02 13:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_coupon_media_order_orderitem_review_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
