# Generated by Django 5.1.4 on 2025-01-02 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('store', '0004_alter_media_options_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='customer.address'),
            preserve_default=False,
        ),
    ]
