# Generated by Django 5.1.4 on 2025-01-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_seller',
            field=models.BooleanField(default=False, verbose_name='Best Seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_arrival',
            field=models.BooleanField(default=False, verbose_name='New Arrival'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='On Sale'),
        ),
    ]
