# Generated by Django 5.1.4 on 2025-01-02 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_best_seller_product_new_arrival_product_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Answer Text')),
                ('active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('date_asked', models.DateTimeField(auto_now_add=True, verbose_name='Date Asked')),
                ('date_answered', models.DateTimeField(blank=True, null=True, verbose_name='Date Answered')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='store.product', verbose_name='Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'ordering': ['-date_asked'],
            },
        ),
    ]
