# Generated by Django 5.1.4 on 2025-01-06 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_vendor'),
        ('vendor', '0003_alter_storereview_user_alter_vendor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__user_type': 'Vendor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='vendor.vendor'),
        ),
    ]
