# Generated by Django 5.1.4 on 2025-01-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping',
        ),
    ]
