# Generated by Django 5.1.4 on 2025-01-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_address_user'),
        ('store', '0019_brand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_servise',
        ),
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.address'),
        ),
    ]
