# Generated by Django 5.1.4 on 2025-01-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_banners_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
