# Generated by Django 5.1.4 on 2025-01-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='variant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='variantitem',
            name='title',
        ),
        migrations.AddField(
            model_name='variant',
            name='variant_type',
            field=models.CharField(choices=[('color', 'Color'), ('size', 'Size'), ('style', 'Style')], default='color', max_length=10),
        ),
        migrations.AddField(
            model_name='variantitem',
            name='title_type',
            field=models.CharField(blank=True, choices=[('color', 'Color'), ('size', 'Size'), ('style', 'Style')], max_length=100, null=True),
        ),
    ]
