# Generated by Django 5.1.4 on 2025-01-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_color_size_style_remove_variant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantitem',
            name='title_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
