# Generated by Django 5.1.4 on 2025-01-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_variantitem_title_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantitem',
            name='title',
            field=models.CharField(blank=True, choices=[], max_length=1000, null=True, verbose_name='Item Title'),
        ),
    ]
