# Generated by Django 5.1.4 on 2025-01-16 18:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_additionalinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalInfo',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=django_ckeditor_5.fields.CKEditor5Field(default=0, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
