# Generated by Django 5.1.4 on 2025-01-16 18:34

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_delete_additionalinfo_product_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_info',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
