# Generated by Django 5.1.4 on 2025-01-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_product_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='variant_type',
        ),
        migrations.RemoveField(
            model_name='variantitem',
            name='title_type',
        ),
        migrations.AddField(
            model_name='variant',
            name='name',
            field=models.CharField(default=0, max_length=1000, verbose_name='Variant name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='item title'),
        ),
    ]
