# Generated by Django 5.1.4 on 2025-01-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_remove_variant_variant_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(choices=[('Color', 'Color'), ('Size', 'Size'), ('Style', 'Style')], default=None, max_length=1000, verbose_name='Variant name'),
        ),
    ]
