# Generated by Django 5.1.4 on 2025-01-17 19:01

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_remove_currency_rate_to_usd_currency_exchange_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='currency',
            name='rate_to_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='store.currency'),
        ),
    ]
