# Generated by Django 5.1.4 on 2025-01-17 21:07

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_alter_product_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video',
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(default=store.models.Currency.get_default_currency, on_delete=django.db.models.deletion.CASCADE, to='store.currency'),
        ),
    ]
