# Generated by Django 5.1.4 on 2025-01-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_videos_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
