# Generated by Django 5.1.4 on 2025-01-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_alter_cartitem_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price_addition',
        ),
    ]
