# Generated by Django 5.1.4 on 2025-01-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_remove_cartitem_price_addition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='price_varinat',
            new_name='price_variant',
        ),
    ]
