# Generated by Django 5.1.4 on 2025-01-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_delete_color_delete_size_delete_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reply',
        ),
    ]
