# Generated by Django 5.1.4 on 2025-01-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_remove_variant_price_variant_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='price_variant_field',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
