# Generated by Django 5.1.4 on 2025-01-23 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='whishlist',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
