# Generated by Django 5.1.4 on 2025-01-17 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_variant_name'),
        ('usauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.currency'),
        ),
    ]
